### PR TITLE
Ignore statinamic-static.js file

### PR DESCRIPTION
**Pull request by thangngoc89**
instead of scripts folder

### CODE REVIEW

**Comment by thangngoc89** [comment]
It looks like master branch is different from my local version. It'll take a look later

**Comment by MoOx** [comment]
Not sure for this change, this file is the server side script and should not be considered as output as it is the script used to generate a part of the output (static html files). Maybe a "build" folder?

**Comment by thangngoc89** [comment]
Yup. Any folder but scripts folder (or I can just add a .gitignore for that file)

**Comment by MoOx** [comment]
There is already a line to ignore it https://github.com/MoOx/statinamic/blob/master/boilerplate/.gitignore#L3
Not working for you?

**Comment by thangngoc89** [comment]
Oops. Sorry, I use my own .gitignore file.
Should be close

**Pull request closed without merging**
