### PR TITLE
Replace console.log and nanoLogger with debug

### LINKED ISSUE #118: Less verbose log in dev mode
This is how my console looks like when starting startinamic on postcss.org

screenshot from 2016-02-10 23 04 15

Maybe replace coonsole.log and nanoLog with [debug](https://www.npmjs.com/package/debug) ?

### PR DESCRIPTION
**Pull request by thangngoc89**
This would close #118

### CODE REVIEW

**Comment by thangngoc89** [comment]
Where are you Travis ?

**Comment by MoOx** [comment]
Looks good. Thanks ! (I assume Travis is on holidays).

**Comment by MoOx** [comment]
Next time try to remember to add something in the CHANGELOG (will do this time).

**Comment by MoOx** [comment]
Adding the DEBUG var in the boilerplate too for now.

**Comment by MoOx** [comment]
I also removed webpack-nano-logs.

**Comment by thangngoc89** [comment]
Yeah. I'll update change log next time

**Pull request merged**
