### PR TITLE
docs: Fix shell command highlight

### PR DESCRIPTION
**Pull request by thangngoc89**
3 aliases for this: bash, sh, zsh.

### CODE REVIEW

**Comment by MoOx** [comment]
This aliases are for shell scripts. This snippets are not scripts. These are terminal (console) commands so it's the correct aliases from what I know.

**Comment by thangngoc89** [comment]
This is no styling in docs right now 

http://moox.io/statinamic/docs/setup/

See https://github.com/isagalaev/highlight.js/blob/master/src/languages/bash.js

**Comment by MoOx** [comment]
It's an issue with the highlighter, not the syntax itself. For example on github it's fine https://github.com/MoOx/statinamic/blob/add524b5ae0f3907080c6049498fdb34c61d4ba1/docs/content/docs/setup.md#create-a-new-folder (even if there is not a lot of colors.

**Comment by thangngoc89** [comment]
Github does support the console keyword https://github.com/github/linguist/blob/d9914307eb4dc306d8312d179cb75c78202f7033/lib/linguist/languages.yml#L3360-L3368

> even if there is not a lot of colors

That's extracly how it will be after this PR. I'm fine with closing this PR (not much colors)

**Comment by MoOx** [comment]
Maybe we should open one on highlight.js ? FYI, console and shell does not produce the same render from what I know.

**Comment by thangngoc89** [comment]
Github calls it shell section.

> FYI, console and shell does not produce the same render from what I know.

Yeah.

**Comment by MoOx** [comment]
Closing in favor of https://github.com/isagalaev/highlight.js/issues/1126

**Pull request closed without merging**
