### PR TITLE
Combine routes, metadata, layouts into exports var on client side

### PR DESCRIPTION
**Pull request by thangngoc89**
As suggested in https://github.com/MoOx/statinamic/pull/145#issuecomment-184228487 , we already doing this in server side (#145)

### CODE REVIEW

**Comment by MoOx** [comment]
Not a fan of this one. We are supposed to remove code, not add more.

**Comment by thangngoc89** [comment]
Can't think of a better way. Webpack will complaint if using `require(require.resolve(...))`

**Comment by MoOx** [comment]
I am just going to revert the thing I asked you in the first place (I will drop exports.js file).

**Comment by thangngoc89** [comment]
Your call. Feel free to close this PR

**Pull request closed without merging**
