### PR TITLE
build: Reliable way to get assets' name

### PR DESCRIPTION
**Pull request by thangngoc89**
Sort assets A-Z for predictable chunks order

### CODE REVIEW

**Comment by MoOx** [comment]
What is the benefit of this as a end user? Not sure what does this brings.

**Comment by thangngoc89** [comment]
You meant the sorting or the way to get assets filename ?

**Comment by thangngoc89** [comment]
For the sorting, webpack always put `manifest` chunk after main chunk. (see long term caching https://github.com/MoOx/statinamic/issues/130#issuecomment-184660624)

**Comment by thangngoc89** [comment]
Getting assetsByChunkName in webpack docs https://github.com/webpack/docs/wiki/long-term-caching#get-filenames-from-stats

**Comment by MoOx** [comment]
Maybe we should manually "sort"? Because is someone add a "Aaaa.js" this will be before manifest.

**Comment by thangngoc89** [comment]
So put manifest as the first element? I think it add more stuff to maintaince. Just tell people that chunks are sorted a-z, named your chunk to get the right order.

**Comment by MoOx** [comment]
I will think about that one more time. I doesn't looks like a intuitive experience...

**Comment by MoOx** [comment]
I guess it's better than nothing.

**Pull request merged**
