### PR TITLE
Add travis cache for node_modules

### PR DESCRIPTION
**Pull request by thangngoc89**
This could speed up build a little speed

### CODE REVIEW

**Comment by MoOx** [comment]
Yeah but you might miss some minor updates/patches that might introduce regressions. Not a fan :/

**Comment by thangngoc89** [comment]
Okie. It's up to you

**Comment by MoOx** [comment]
I think it's better to way maybe a little longer, but that might help us catch regressions due to deps changes more quickly!

**Comment by MoOx** [comment]
Thanks!

**Pull request closed without merging**
