### PR TITLE
Backport master changes to next

### PR DESCRIPTION
**Pull request by MoOx**

### CODE REVIEW

**Comment by MoOx** [comment]
Well maybe not the best idea I had.

**Comment by thangngoc89** [comment]
This is easier than the other way.

**Comment by MoOx** [comment]
The other way is #300 and it's not easier since they are conflicts, the same conflicts.

**Comment by MoOx** [comment]
Not sure if merging master into next and then merging next into master make more sense.
I will unprotect and rebase next on master.

**Comment by thangngoc89** [comment]
I won't mess with #300. That's a can of worms

**Pull request closed without merging**
