### PR TITLE
Bump stylelint@^5.0.1 and stylelint-config-standard@^4.0.1

### PR DESCRIPTION
**Pull request by thangngoc89**

### CODE REVIEW

**Comment by MoOx** [comment]
Can you rebase + add a note in the CHANGELOG under a `##Boilerplate ` ?

**Comment by thangngoc89** [comment]
I saw you rebased this branch. Do I need to do anything now ?

**Comment by MoOx** [comment]
waiting for CI

**Comment by thangngoc89** [comment]
:+1:

**Pull request merged**
