### PR TITLE
Remove AVA serial script

### PR DESCRIPTION
**Pull request by thangngoc89**
I added a fail test in this PR so unit tests should fail. :/

### CODE REVIEW

**Comment by thangngoc89** [comment]
@MoOx I'm not sure why I'm throwing on main process but the process doesn't exit. Can you take a look ?

**Comment by MoOx** [comment]
Use setTimeout to throw when in a promise

**Comment by thangngoc89** [comment]
> Use setTimeout to throw when in a promise

Nice catch. But I prefer setImmediate. It's cleaner.

**Comment by thangngoc89** [comment]
It doesn't fail when run in serial mode 

https://travis-ci.org/MoOx/statinamic/jobs/122192604

**Comment by ben-eb** [comment]
Heh, nice one. :+1:

**Comment by thangngoc89** [comment]
Craps. Unit tests fail on Windows all the time without us knowing about it.

Shame :( 

I saw this error message before when enabling node 4 on Appveyor

**Comment by MoOx** [comment]
If AVA is so annoying and does not fix perf issue soon, I am going to use tape again. We should not loose time on this shit :'(
Or we can get rid of node 4 for now, until they fix their issues.

**Comment by thangngoc89** [comment]
Yes. I'm losing so much time on AVA and node 4. I saw the perf issue was assigned. Maybe please wait a little longer. I'm too lazy to learn another test runner

**Comment by MoOx** [comment]
FYI, AVA is highly inspired by [tape](https://github.com/substack/tape).
Anyway, I think we should remove this way to run AVA tests, and skip node 4 until they fix https://github.com/sindresorhus/ava/issues/78

**Comment by thangngoc89** [comment]
Haha. looks like AVA 0.14 has some performance improvements. All tests passed

**Comment by thangngoc89** [comment]
This blocks other PR so I merge this :)

**Pull request merged**
