### PR TITLE
Fix coverage report on CI

### PR DESCRIPTION
**Pull request by thangngoc89**
It's good to have coverage report back.

Right @codecov-io ?

### CODE REVIEW

**Comment by MoOx** [comment]
why is this weird change required?

**Comment by thangngoc89** [comment]
It's AVA who spawn those processes, not `npm run`. nyc 6.0.0 isn't required 

Hang on a sec. nyc doesn't ignore test files

**Comment by MoOx** [comment]
It was working before right?

**Comment by thangngoc89** [comment]
@MoOx yes. It was working before. No idea why it's stop working

**Comment by thangngoc89** [comment]
Related ? https://github.com/bcoe/nyc/issues/190

**Comment by arrowrowe** [comment]
@thangngoc89 I cannot understand what causes #190. The problem is, in short, no coverage files found only using Node 5.8.0 and NPM 3.7.3. This problem disappears after updating NPM  to 3.8.1 or using Node 5.7.1 instead.

**Comment by thangngoc89** [comment]
@arrowrowe We are having the same problem here. node 4 is fine. Push a new commit to use latest npm

**Comment by arrowrowe** [comment]
@thangngoc89 Thanks! Trying it now.

**Comment by thangngoc89** [comment]
@MoOx upgrading npm to latest version (3.8.1) did help 

https://travis-ci.org/MoOx/statinamic/builds/115487336#L654-L728

**Comment by arrowrowe** [comment]
@thangngoc89 It works for me as well. Thanks!

**Comment by MoOx** [comment]
So no need for this PR right?

**Comment by thangngoc89** [comment]
@MoOx We can wait until 

- nyc fixes this bug
- or a new node release which uses npm@3.8.1

**Comment by MoOx** [comment]
latest node don't get npm@^3.0.0 ? They fix the version to 3.7.x ?

**Comment by thangngoc89** [comment]
latest node is 3.8.1 https://travis-ci.org/MoOx/statinamic/builds/115487336#L215

**Comment by MoOx** [comment]
npm*

But does latest node ship this version? It seems latest node ship 3.7.x  https://github.com/nodejs/node/tree/master/deps/npm (or https://github.com/nodejs/node/tree/v5.x/deps/npm )

**Comment by MoOx** [comment]
Oh my bad. I just looked at the nyc mentionned issue. So not sure what to do.

**Comment by MoOx** [comment]
We get your patch for now. Can you add a comment in it ?

**Comment by thangngoc89** [comment]
Added comment

**Comment by MoOx** [comment]
:+1:

**Pull request merged**
