### PR TITLE
Master failed ?

### PR DESCRIPTION
**Pull request by thangngoc89**
Don't bother with the code. I just want to trigger a Travis build on master again.

Why ? I haven't touch my blog's code (which uses statinamic) for weeks. And suddenly, on a fresh clone, it fails.

I traced it down to this line https://github.com/MoOx/statinamic/blob/master/src/client/index.js#L4

This was fixed in #113 .

### CODE REVIEW

**Comment by thangngoc89** [comment]
Well. Travis failed with a different bug. This may be introduced with babel@6.5.1. 
greenkeeper's pr for babel-cli@6.5.1 fails on a different project of mind with the same error

https://travis-ci.org/thangngoc89/react-code-playground/jobs/107690164#L149

**Comment by MoOx** [comment]
Don't worry, I will catch up will all small issues after merging the big PR (I hope this evening or tomorrow morning).

**Comment by thangngoc89** [comment]
which timezone are you ?

**Comment by MoOx** [comment]
gmt+1 :) (it's 8pm as I am writing this, just starting my evening ;) )

**Comment by MoOx** [comment]
Getting this one with ava too.

**Comment by thangngoc89** [comment]
Super weird

**Comment by MoOx** [comment]
So related to babel upgrade.

https://github.com/istarkov/babel-plugin-webpack-loaders/issues/15
https://github.com/sindresorhus/ava/issues/538

**Pull request closed without merging**
