### PR TITLE
Use babel-register instead of babel-core/register

### LINKED ISSUE #335: Missing babel-register in dep
We only have babel-core, not babel-register so this will break stuff.

This is also a good chance to replace `babel-core/register` with `babel-register`. (will be deprecated soon)

### PR DESCRIPTION
**Pull request by thangngoc89**
Close #335

### CODE REVIEW

**Comment by thangngoc89** [comment]
This must be release at 0.10.0 (breaking change)

**Comment by MoOx** [comment]
Why this should be  a breaking change? It's used internally only. Should just be a dep.

**Comment by thangngoc89** [comment]
> Why this should be a breaking change?

I added a peer dep.

> It's used internally only. Should just be a dep.

we don't put babel stuff in dep. I'm trying to avoid duplicate package here.

**Comment by MoOx** [comment]
Stuff used internally should be in deps. Anyway I don't think we are going to use this  for long (ref #301).
Please put in dep so we can release as a fix.

**Comment by thangngoc89** [comment]
PR updated.

**Pull request merged**
