### PR TITLE
0.8.0

### PR DESCRIPTION
**Pull request by MoOx**
I will try to handle #11 quickly, and if I fails with a dirty hack I will merge and release this, after adding instruction on how to migrate to the new `exports` thing.

### CODE REVIEW

**Comment by thangngoc89** [comment]
I'm working on unify exports on client side. Diff should be small. Give me a minute

**Comment by MoOx** [comment]
No hurry ;)

**Comment by thangngoc89** [comment]
Also take a look at #158 , it should not break anything :) .

**Comment by MoOx** [comment]
I pushed a bunch of stuff.

**Comment by thangngoc89** [comment]
Oh. We have markdown hot loading ? Awesome :dancer:

**Comment by thangngoc89** [comment]
Something wrong with new docs PageError 

```
Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `PageError`. See https://fb.me/react-warning-keys for more information

validateDOMNesting(...): <h1> cannot appear as a descendant of <p>. See PageError > p > ... > h1.
```

**Comment by MoOx** [comment]
We just need to handle #67 in PageContainer and then make a release.

**Comment by thangngoc89** [comment]
Use a local fork of catch link and wait for that issue resolve then switch back to main repo ?

**Comment by MoOx** [comment]
Yeah.

**Comment by thangngoc89** [comment]
New PR is comming ....

**Comment by MoOx** [comment]
Current implementation of the catch-links method sucks cause you can't link to an assets, react-router catch it (so we got a 404)...
Maybe PageContainer should redirect if not in the collection?!

**Comment by thangngoc89** [comment]
Ouch. Never think of that. Yes. PageContainer should do the redirect.

**Comment by MoOx** [comment]
Will merge and release tomorrow morning (after my night ^^)

**Comment by thangngoc89** [comment]
@MoOx take a look at 404 page. React is warning about no key when render an array

**Comment by MoOx** [comment]
Hum I don't have this warning. Will double check.

**Comment by thangngoc89** [comment]
Cannot find module 'classnames' . You should put `classnames` to deps field instead of devDeps  (something like #117 )

**Comment by MoOx** [comment]
@thangngoc89 classnames is in devdeps. Not enough?

**Comment by MoOx** [comment]
oh yeah dep. Oups.

**Comment by thangngoc89** [comment]
:+1: new homepage looking good. I don't know if this is related to the catch links hack. But I can return to homepage after watching the video.

Reproduce:

- Click the image on homepage
- Watch video
- Click `back` , url changed to `0.0.0.0:3000/statinamic/` but I'm still watching the video. (no matter how manytimes I click that back button)


Btw. Test is failing :)

**Comment by MoOx** [comment]
@thangngoc89 I got that bug too. Not sure what is to blame :/

**Comment by MoOx** [comment]
I used window.location.reload() maybe that's the reason. I will try something else.

**Comment by thangngoc89** [comment]
I'm not happy with the implementation of catch links. Something, it shows up a 404 page for no reason

**Comment by MoOx** [comment]
I got that issue too.

**Comment by thangngoc89** [comment]
Maybe change all link in docs from relative to absolute ? 

`../usage/` --> `/docs/usage/`

**Comment by MoOx** [comment]
We can't ask people to only use absolute link. This has to be fixed.

**Comment by thangngoc89** [comment]
Okie. Gotta go. Hope 0.8.0 will be released soon.

**Comment by MoOx** [comment]
I will cut a release. I cannot reproduce the weird 404 bug.

**Comment by thangngoc89** [comment]
I'll investigate it and write a proper issue

**Comment by MoOx** [comment]
Appveyor hasn't finished yet (queued) but I can't wait :clap:

**Comment by thangngoc89** [comment]
Congrats :clap:

**Comment by thangngoc89** [comment]
Some issues don't auto close

**Comment by MoOx** [comment]
It's because I changed next to be the default branch. I will do by hand. First I am fixing a regression due to react-router basename (hot loading for md is broken).

**Comment by thangngoc89** [comment]
Okie. I can we miss that

**Comment by thangngoc89** [comment]
I'll update my blog to 0.8.0, maybe we can use it as a diff for people who want to upgrade

**Pull request merged**
