### PR TITLE
Update to Babel 6

### PR DESCRIPTION
**Pull request by mxstbr**
WIP

For some reason the `npm run test` fails – any idea why?

### CODE REVIEW

**Comment by MoOx** [comment]
It will be a bit more complicated since we have to handle peerdeps and also deps of the docs/ part that use the parent folder as a node_modules (statinamic use itself for its doc)

**Comment by mxstbr** [comment]
Can you point me in a direction of what to do?

**Comment by MoOx** [comment]
You need to update peerDependencies versions too, and also update the docs/package.json.
And please try to not commit changes for the eslint config.
Also I would like to keep babel config in package.json to avoid the .*rc hell :)

**Comment by mxstbr** [comment]
Alright, will take another look in the afternoon! 

Didn't even notice the eslint config changes, any idea how they happened? I didn't change it...

**Comment by MoOx** [comment]
Each time you run an npm command that adjust the package.json, this section is updated. I will outsource this config as a eslint shareable package to avoid that because it's a pain in the arse :)

**Comment by mxstbr** [comment]
:+1: airbnb/javascript maybe?

**Comment by iamstarkov** [comment]
👍 for airbnb/javascript

**Comment by MoOx** [comment]
I am on it since I am currently upgrading lot of things (tape>ava which use Babel 6...) in order to be able to have a code coverage percentage :)

**Comment by mxstbr** [comment]
:+1:

**Pull request closed without merging**
