### PR TITLE
Run integration-tests in tests

### LINKED ISSUE #345: Integration tests aren't run in CI

### PR DESCRIPTION
**Pull request by MoOx**
Closes #345

### CODE REVIEW

**Comment by thangngoc89** [comment]
@MoOx It run forever

**Comment by MoOx** [comment]
f*** the kill just don't work. I got this issue a long time ago on travis...

**Comment by thangngoc89** [comment]
>  the kill just don't work

I can reproduce it locally 

See https://github.com/MoOx/statinamic/pull/340#issuecomment-199680120

**Comment by MoOx** [comment]
Not me

```
~/Sync/Development/statinamic fix/ci-it
❯ ava __tests__/*.js  

  ✖ index › should have a CSS file   
  t.is(files.filter(file => file.startsWith("statinamic-client.") && file.endsWith(".css")).length, 1)
                                                                                            |         
                                                                                            0         
  
  ✔ cli › should NOT throw if a CLI flag is recognized (509ms)
  ✖ cli › should throw if a CLI flag is NOT recognized   
  t.ok(err.message.indexOf("Unknown option `--lol'") > -1)
                   |                                      
                   -1                                     
  

  2 tests failed

  1. cli › should throw if a CLI flag is NOT recognized
  AssertionError: false == true
    cli.js:20:11
    tryCallOne (/Users/MoOx/Sync/Development/statinamic/node_modules/promise/lib/core.js:37:12)
    /Users/MoOx/Sync/Development/statinamic/node_modules/promise/lib/core.js:123:15
    flush (/Users/MoOx/Sync/Development/statinamic/node_modules/asap/raw.js:50:29)
    
  2. index › should have a CSS file
  AssertionError: 0 === 1
    Test.fn (index.js:10:5)
    


~/Sync/Development/statinamic fix/ci-it 6s
```

**Comment by thangngoc89** [comment]
Did you run `npm run test-boilerplate`

Webpack will clean the dist folder after each test

**Comment by MoOx** [comment]
nvm I said shit

**Comment by MoOx** [comment]
integration tests will now be run, but I cannot validate cli args for now, see #363.

**Comment by thangngoc89** [comment]
I rebased this branch and add a (possible) fix for Windows shit

**Comment by MoOx** [comment]
Now broken on Travis lol

**Comment by thangngoc89** [comment]
Some issue with caching. But I can't clean cache in Travis. Error while loading

**Comment by MoOx** [comment]
:+1:

**Pull request merged**
