### PR TITLE
Add option to bundle collection into html

### PR DESCRIPTION
**Pull request by thangngoc89**
This PR add an option to bundle collection to html

ref #92 #96 

Usage:

```
// index.md
---
layout: Homepage
title: Home page
collection: true
---
```

I'm replying on Travis for test right now, because ava freezes my laptop

### CODE REVIEW

**Comment by MoOx** [comment]
I think this should be default behavior. I don't want a weird "collection" option in meta (and you don't want neither, am I right?).
Maybe a "collection: false" to disable in frontmatter, and a collection: true by default in js config?

Also you will need to adjust the useless fetch for the collection.json file if the collection is already in the initial state.

**Comment by MoOx** [comment]
Did you try "ava src/ a single file.js" to run test?

**Comment by thangngoc89** [comment]
Oh yeah. you are right. this should be the default behavior.

**Comment by thangngoc89** [comment]
Oops. Accidentally delete this branch. Continue as #100

**Pull request closed without merging**
