### PR TITLE
Fix build script

### PR DESCRIPTION
**Pull request by thangngoc89**
FYI, you are serving raw script in docs site

### CODE REVIEW

**Comment by MoOx** [comment]
I will review this because some others flag use prod and should use production. (eg: `__PROD__`).

**Comment by thangngoc89** [comment]
Well. Or just add -- prod in build script 

https://github.com/MoOx/statinamic/blob/master/docs/package.json#L55
becomes `babel-node scripts/build --static --production --prod`

That's faster

**Comment by MoOx** [comment]
--production --prod... Hum.
production or prod? One should be enough.

**Comment by thangngoc89** [comment]
Haha. That's why I file this PR

**Comment by thangngoc89** [comment]
Close in favor of #113

**Pull request closed without merging**
