### PR TITLE
Update setup command in docs

### PR DESCRIPTION
**Pull request by thangngoc89**
The original command will create a boilerplate folder inside $DIR

### CODE REVIEW

**Comment by MoOx** [comment]
Weird. I was pretty sure I double checked this (there was no slash at first in the doc, if my memory is correct).

**Comment by MoOx** [comment]
Are you sure you didn't miss the / ?

```console
~/Sync/Development/statinamic master
❯ mkdir test

~/Sync/Development/statinamic master ⇣
❯ cp -R ./boilerplate test   

~/Sync/Development/statinamic master* ⇣
❯ ls test
boilerplate

~/Sync/Development/statinamic master* ⇣
❯ cp -R ./boilerplate/ test

~/Sync/Development/statinamic master* ⇣
❯ ls test
README.md    boilerplate  content      dist         node_modules package.json scripts      web_modules
```

**Comment by thangngoc89** [comment]
You forgot that there is node_modules and package.json file inside that folder. 

Let's try a more "real-world" example

```shell
✔ ~/web/statinamic [master|⚑ 7] 
17:51 $ mkdir test
✔ ~/web/statinamic [master|⚑ 7] 
17:52 $ rm -rf test
✔ ~/web/statinamic [master|⚑ 7] 
17:52 $ mkdir -p test/node_modules && touch test/package.json
✔ ~/web/statinamic [master|…1⚑ 7] 
17:53 $ ls test
node_modules  package.json
✔ ~/web/statinamic [master|…1⚑ 7] 
17:53 $ cp -R ./boilerplate/ test
✔ ~/web/statinamic [master|…24⚑ 7] 
17:53 $ ls test
boilerplate  node_modules  package.json
✔ ~/web/statinamic [master|…24⚑ 7] 
17:53 $ cp -R ./boilerplate/* test
✔ ~/web/statinamic [master|…46⚑ 7] 
17:53 $ ls test
boilerplate  node_modules  README.md  web_modules
content      package.json  scripts

```

**Comment by MoOx** [comment]
node_modules and package.json are in this repo, not versionned, so not published in "real-world" :)

**Comment by thangngoc89** [comment]
No. I mean in the setup instruction. User have to create package.json file first and then install statinamic. This will create package.json and node_modules.  Just try the setup instruction and you'll see the result

**Comment by thangngoc89** [comment]
Anyway,  this is *nix specific command,  not compat with windows cmd/powershell,  i'm working on a different branch to improve the setup progress painless:

```sh
mkdir foo && cd foo
npm i statinamic
./node_modules/.bin/statinamic setup
# ask some questions
# done

```

**Pull request closed without merging**
