### PR TITLE
Improve code coverage to 70%

### PR DESCRIPTION
**Pull request by thangngoc89**

### CODE REVIEW

**Comment by thangngoc89** [comment]
@MoOx codecov is drunk

**Comment by MoOx** [comment]
Ready or not?

**Comment by thangngoc89** [comment]
Not ready yet. I'll poke you when it's rady

**Comment by MoOx** [comment]
Maybe we should iterate slowly? Just send a PR for each files you update/write?

**Comment by thangngoc89** [comment]
If that is the case,  you can merge this now.

**Pull request merged**
