### PR TITLE
Rename project to Phenomic

### LINKED ISSUE #306: Change name of the project 😢
EDIT:

Plans:

- [x] rename repo and all occurences in repo
- [ ] npm deprecate
- [ ] redirect doc from https://duckduckgo.com/?q=site%3Amoox.io%2Fstatinamic%2F&t=ffab to phenomic.io/*
- [x] switch twitter nick for statinamic and phenomic_app (goal: keep statinamic mention and pin a tweet to redirect people to phenomic_app account)
- [ ] add in the README and doc a mention to the old name for a moment.

---

When I started this project I was unsure about the name. And it seems I was not alone.
I received this legitimate email from [statamic](http://statamic.com/) author

> Hey Maxime, I just saw that you’ve been building a static site generator called statinamic. It looks neat. However, it’s extremely close to -- in name and purpose — my static/flat file CMS Statamic, which has been on the market since 2012. I don’t this to turn into a big thing, so I was hoping a little email might prompt you to think about renaming it. Let me just say from experience, people have a hard time saying the combination of these two words. You might even do better in the long run giving it a clever javascript-ecosystem name like “ThunderGen” or “Electro” or something. You know the drill.
>
> Thanks for you time. I wish you the best, please let me know when you get this and what you plan to do so I can plan accordingly. I much prefer to be friends with everybody!

Facts:

- statinamic has been reported to be hard to pronouce in english (however in french or Vietnamese, no problem)
- the name is too similar to a project that have a similar goal (make a website from some content).

So please share your ideas, there is no bad idea, only ideas (even the worst one will affect the final choice).

Here are some requirements:
- name is available on npm (try https://www.npmjs.com/package/THE_NAME)
- name is available on a domain that does nut suck (eg: .org, .io etc, no .beer or .website)
- name is not a generic name (I want something that have some "personality")

### PR DESCRIPTION
**Pull request by MoOx**
Before merging this we have to

- [x] add migrations commands in CHANGELOG
- [x] add note in README and in website header
- [x] update logo

After merging this we have to

- [ ] rename this repo
- [ ] Cut a release
- [ ] deprecate statinamic on npm
- [ ] add the redirection on moox.io `https://moox.io/statinamic/*` to `https://phenomic.io/$1`.
- [ ] drop https://github.com/MoOx/phenomic-tmp that use phenomic.io CNAME
- [ ] update master branch

Should be good after that.

Will close #306.

### CODE REVIEW

**Comment by thangngoc89** [comment]
Looking goods :D 

Anything before merging this ?

**Comment by MoOx** [comment]
Let me try this on a website before :)

**Comment by MoOx** [comment]
If tests are ok (they should), I will merge this and cut the release :)

**Comment by MoOx** [comment]
FYI screen shot 2016-04-13 at 17 10 56

**Comment by magsout** [comment]
👍

**Pull request merged**
